#!/bin/bash
#velvet cross assemblies

#v1S1Xv2S1
velveth /scratch/cputonti/v1S1Xv2S1 29 -short -fasta /data/cputonti/v1_S1.fa /data/cputonti/v2_S1/contigs.fa

velvetg /scratch/cputonti/v1S1Xv2S1 -exp_cov auto

#v1S1Xv2S2
velveth /scratch/cputonti/v1S1Xv2S2 29 -short -fasta /data/cputonti/v1_S1.fa /data/cputonti/v2_S1/contigs.fa

velvetg /scratch/cputonti/v1S1Xv2S2 -exp_cov auto

#v1S1Xv2S3
velveth /scratch/cputonti/v1S1Xv2S3 29 -short -fasta /data/cputonti/v1_S1.fa /data/cputonti/v2_S3/contigs.fa

velvetg /scratch/cputonti/v1S1Xv2S3 -exp_cov auto

#v1S1Xv2S4
velveth /scratch/cputonti/v1S1Xv2S4 29 -short -fasta /data/cputonti/v1_S1.fa /data/cputonti/v2_S4/contigs.fa

velvetg /scratch/cputonti/v1S1Xv2S4 -exp_cov auto

#v1S1Xv2S5
velveth /scratch/cputonti/v1S1Xv2S5 29 -short -fasta /data/cputonti/v1_S1.fa /data/cputonti/v2_S5/contigs.fa

velvetg /scratch/cputonti/v1S1Xv2S5 -exp_cov auto

#v1S1Xv2S6
velveth /scratch/cputonti/v1S1Xv2S6 29 -short -fasta /data/cputonti/v1_S1.fa /data/cputonti/v2_S6/contigs.fa

velvetg /scratch/cputonti/v1S1Xv2S6 -exp_cov auto

#v1S1Xv2S7
velveth /scratch/cputonti/v1S1Xv2S7 29 -short -fasta /data/cputonti/v1_S1.fa /data/cputonti/v2_S7/contigs.fa

velvetg /scratch/cputonti/v1S1Xv2S7 -exp_cov auto

#v1S1Xv2S8
velveth /scratch/cputonti/v1S1Xv2S8 29 -short -fasta /data/cputonti/v1_S1.fa /data/cputonti/v2_S8/contigs.fa

velvetg /scratch/cputonti/v1S1Xv2S8 -exp_cov auto

#v1S1Xv2S9
velveth /scratch/cputonti/v1S1Xv2S9 29 -short -fasta /data/cputonti/v1_S1.fa /data/cputonti/v2_S9/contigs.fa

velvetg /scratch/cputonti/v1S1Xv2S9 -exp_cov auto

#v1S1Xv2S10
velveth /scratch/cputonti/v1S1Xv2S10 29 -short -fasta /data/cputonti/v1_S1.fa /data/cputonti/v2_S10/contigs.fa

velvetg /scratch/cputonti/v1S1Xv2S10 -exp_cov auto

#v1S1Xv2S11
velveth /scratch/cputonti/v1S1Xv2S11 29 -short -fasta /data/cputonti/v1_S1.fa /data/cputonti/v2_S11/contigs.fa

velvetg /scratch/cputonti/v1S1Xv2S11 -exp_cov auto

#v1S2Xv2S1
velveth /scratch/cputonti/v1S2Xv2S1 29 -short -fasta /data/cputonti/v1_S2.fa /data/cputonti/v2_S1/contigs.fa

velvetg /scratch/cputonti/v1S2Xv2S1 -exp_cov auto

#v1S2Xv2S2
velveth /scratch/cputonti/v1S2Xv2S2 29 -short -fasta /data/cputonti/v1_S2.fa /data/cputonti/v2_S2/contigs.fa

velvetg /scratch/cputonti/v1S2Xv2S2 -exp_cov auto

#v1S2Xv2S3
velveth /scratch/cputonti/v1S2Xv2S3 29 -short -fasta /data/cputonti/v1_S2.fa /data/cputonti/v2_S3/contigs.fa

velvetg /scratch/cputonti/v1S2Xv2S3 -exp_cov auto

#v1S2Xv2S4
velveth /scratch/cputonti/v1S2Xv2S4 29 -short -fasta /data/cputonti/v1_S2.fa /data/cputonti/v2_S4/contigs.fa

velvetg /scratch/cputonti/v1S2Xv2S4 -exp_cov auto

#v1S2Xv2S5
velveth /scratch/cputonti/v1S2Xv2S5 29 -short -fasta /data/cputonti/v1_S2.fa /data/cputonti/v2_S5/contigs.fa

velvetg /scratch/cputonti/v1S2Xv2S5 -exp_cov auto

#v1S2Xv2S6
velveth /scratch/cputonti/v1S2Xv2S6 29 -short -fasta /data/cputonti/v1_S2.fa /data/cputonti/v2_S6/contigs.fa

velvetg /scratch/cputonti/v1S2Xv2S6 -exp_cov auto

#v1S2Xv2S7
velveth /scratch/cputonti/v1S2Xv2S7 29 -short -fasta /data/cputonti/v1_S2.fa /data/cputonti/v2_S7/contigs.fa

velvetg /scratch/cputonti/v1S2Xv2S7 -exp_cov auto

#v1S2Xv2S8
velveth /scratch/cputonti/v1S2Xv2S8 29 -short -fasta /data/cputonti/v1_S2.fa /data/cputonti/v2_S8/contigs.fa

velvetg /scratch/cputonti/v1S2Xv2S8 -exp_cov auto

#v1S2Xv2S9
velveth /scratch/cputonti/v1S2Xv2S9 29 -short -fasta /data/cputonti/v1_S2.fa /data/cputonti/v2_S4/contigs.fa

velvetg /scratch/cputonti/v1S2Xv2S4 -exp_cov auto

#v1S2Xv2S10
velveth /scratch/cputonti/v1S2Xv2S10 29 -short -fasta /data/cputonti/v1_S2.fa /data/cputonti/v2_S10/contigs.fa

velvetg /scratch/cputonti/v1S2Xv2S10 -exp_cov auto

#v1S2Xv2S11
velveth /scratch/cputonti/v1S2Xv2S11 29 -short -fasta /data/cputonti/v1_S2.fa /data/cputonti/v2_S11/contigs.fa

velvetg /scratch/cputonti/v1S2Xv2S11 -exp_cov auto

#v1S3Xv2S1
velveth /scratch/cputonti/v1S3Xv2S1 29 -short -fasta /data/cputonti/v1_S3.fa /data/cputonti/v2_S1/contigs.fa

velvetg /scratch/cputonti/v1S3Xv2S1 -exp_cov auto

#v1S3Xv2S2
velveth /scratch/cputonti/v1S3Xv2S2 29 -short -fasta /data/cputonti/vv1_S3.fa /data/cputonti/v2_S2/contigs.fa

velvetg /scratch/cputonti/v1S3Xv2S2 -exp_cov auto

#v1S3Xv2S3
velveth /scratch/cputonti/v1S3Xv2S3 29 -short -fasta /data/cputonti/v1_S3.fa /data/cputonti/v2_S3/contigs.fa

velvetg /scratch/cputonti/v1S3Xv2S3 -exp_cov auto

#v1S3Xv2S4
velveth /scratch/cputonti/v1S3Xv2S4 29 -short -fasta /data/cputonti/v1_S3.fa /data/cputonti/v2_S4/contigs.fa

velvetg /scratch/cputonti/v1S3Xv2S4 -exp_cov auto

#v1S3Xv2S5
velveth /scratch/cputonti/v1S3Xv2S5 29 -short -fasta /data/cputonti/v1_S3.fa /data/cputonti/v2_S5/contigs.fa

velvetg /scratch/cputonti/v1S3Xv2S5 -exp_cov auto

#v1S3Xv2S6
velveth /scratch/cputonti/v1S3Xv2S6 29 -short -fasta /data/cputonti/v1_S3.fa /data/cputonti/v2_S6/contigs.fa

velvetg /scratch/cputonti/v1S3Xv2S6 -exp_cov auto

#v1S3Xv2S7
velveth /scratch/cputonti/v1S3Xv2S7 29 -short -fasta /data/cputonti/v1_S3.fa /data/cputonti/v2_S7/contigs.fa

velvetg /scratch/cputonti/v1S3Xv2S7 -exp_cov auto

#v1S3Xv2S8
velveth /scratch/cputonti/v1S3Xv2S8 29 -short -fasta /data/cputonti/v1_S3.fa /data/cputonti/v2_S8/contigs.fa

velvetg /scratch/cputonti/v1S3Xv2S8 -exp_cov auto

#v1S3Xv2S9
velveth /scratch/cputonti/v1S3Xv2S9 29 -short -fasta /data/cputonti/v1_S3.fa /data/cputonti/v2_S9/contigs.fa

velvetg /scratch/cputonti/v1S3Xv2S9 -exp_cov auto

#v1S3Xv2S10
velveth /scratch/cputonti/v1S3Xv2S10 29 -short -fasta /data/cputonti/v1_S3.fa /data/cputonti/v2_S10/contigs.fa

velvetg /scratch/cputonti/v1S3Xv2S10 -exp_cov auto

#v1S3Xv2S11
velveth /scratch/cputonti/v1S3Xv2S11 29 -short -fasta /data/cputonti/v1_S3.fa /data/cputonti/v2_S11/contigs.fa

velvetg /scratch/cputonti/v1S3Xv2S11 -exp_cov auto

#v1S4Xv2S1
velveth /scratch/cputonti/v1S4Xv2S1 29 -short -fasta /data/cputonti/v1_S4.fa /data/cputonti/v2_S1/contigs.fa

velvetg /scratch/cputonti/v1S4Xv2S1 -exp_cov auto

#v1S4Xv2S2
velveth /scratch/cputonti/v1S4Xv2S2 29 -short -fasta /data/cputonti/v1_S4.fa /data/cputonti/v2_S2/contigs.fa

velvetg /scratch/cputonti/v1S4Xv2S2 -exp_cov auto

#v1S4Xv2S3
velveth /scratch/cputonti/v1S4Xv2S3 29 -short -fasta /data/cputonti/v1_S4.fa /data/cputonti/v2_S3/contigs.fa

velvetg /scratch/cputonti/v1S4Xv2S3 -exp_cov auto

#v1S4Xv2S4
velveth /scratch/cputonti/v1S4Xv2S4 29 -short -fasta /data/cputonti/v1_S4.fa /data/cputonti/v2_S4/contigs.fa

velvetg /scratch/cputonti/v1S4Xv2S4 -exp_cov auto

#v1S4Xv2S5
velveth /scratch/cputonti/v1S4Xv2S5 29 -short -fasta /data/cputonti/v1_S4.fa /data/cputonti/v2_S5/contigs.fa

velvetg /scratch/cputonti/v1S4Xv2S5 -exp_cov auto

#v1S4Xv2S6
velveth /scratch/cputonti/v1S4Xv2S6 29 -short -fasta /data/cputonti/v1_S4.fa /data/cputonti/v2_S6/contigs.fa

velvetg /scratch/cputonti/v1S4Xv2S6 -exp_cov auto

#v1S4Xv2S7
velveth /scratch/cputonti/v1S4Xv2S7 29 -short -fasta /data/cputonti/v1_S4.fa /data/cputonti/v2_S7/contigs.fa

velvetg /scratch/cputonti/v1S4Xv2S7 -exp_cov auto

#v1S4Xv2S8
velveth /scratch/cputonti/v1S4Xv2S8 29 -short -fasta /data/cputonti/v1_S4.fa /data/cputonti/v2_S8/contigs.fa

velvetg /scratch/cputonti/v1S4Xv2S8 -exp_cov auto

#v1S4Xv2S9
velveth /scratch/cputonti/v1S4Xv2S9 29 -short -fasta /data/cputonti/v1_S4.fa /data/cputonti/v2_S9/contigs.fa

velvetg /scratch/cputonti/v1S4Xv2S9 -exp_cov auto

#v1S4Xv2S10
velveth /scratch/cputonti/v1S4Xv2S10 29 -short -fasta /data/cputonti/v1_S4.fa /data/cputonti/v2_S10/contigs.fa

velvetg /scratch/cputonti/v1S4Xv2S10 -exp_cov auto

#v1S4Xv2S11
velveth /scratch/cputonti/v1S4Xv2S11 29 -short -fasta /data/cputonti/v1_S4.fa /data/cputonti/v2_S11/contigs.fa

velvetg /scratch/cputonti/v1S4Xv2S11 -exp_cov auto

#v1S5Xv2S1
velveth /scratch/cputonti/v1S5Xv2S1 29 -short -fasta /data/cputonti/v1_S5.fa /data/cputonti/v2_S1/contigs.fa

velvetg /scratch/cputonti/v1S5Xv2S1 -exp_cov auto

#v1S5Xv2S2
velveth /scratch/cputonti/v1S5Xv2S2 29 -short -fasta /data/cputonti/v1_S5.fa /data/cputonti/v2_S2/contigs.fa

velvetg /scratch/cputonti/v1S5Xv2S2 -exp_cov auto

#v1S5Xv2S3
velveth /scratch/cputonti/v1S5Xv2S3 29 -short -fasta /data/cputonti/v1_S5.fa /data/cputonti/v2_S3/contigs.fa

velvetg /scratch/cputonti/v1S5Xv2S3 -exp_cov auto

#v1S5Xv2S4
velveth /scratch/cputonti/v1S5Xv2S4 29 -short -fasta /data/cputonti/v1_S5.fa /data/cputonti/v2_S4/contigs.fa

velvetg /scratch/cputonti/v1S5Xv2S4 -exp_cov auto

#v1S5Xv2S5
velveth /scratch/cputonti/v1S5Xv2S5 29 -short -fasta /data/cputonti/v1_S5.fa /data/cputonti/v2_S5/contigs.fa

velvetg /scratch/cputonti/v1S5Xv2S5 -exp_cov auto

#v1S5Xv2S6
velveth /scratch/cputonti/v1S5Xv2S6 29 -short -fasta /data/cputonti/v1_S5.fa /data/cputonti/v2_S6/contigs.fa

velvetg /scratch/cputonti/v1S5Xv2S6 -exp_cov auto

#v1S5Xv2S7
velveth /scratch/cputonti/v1S5Xv2S7 29 -short -fasta /data/cputonti/v1_S5.fa /data/cputonti/v2_S7/contigs.fa

velvetg /scratch/cputonti/v1S5Xv2S7 -exp_cov auto

#v1S5Xv2S8
velveth /scratch/cputonti/v1S5Xv2S8 29 -short -fasta /data/cputonti/v1_S5.fa /data/cputonti/v2_S8/contigs.fa

velvetg /scratch/cputonti/v1S5Xv2S8 -exp_cov auto

#v1S5Xv2S9
velveth /scratch/cputonti/v1S5Xv2S9 29 -short -fasta /data/cputonti/v1_S5.fa /data/cputonti/v2_S9/contigs.fa

velvetg /scratch/cputonti/v1S5Xv2S9 -exp_cov auto

#v2S1Xv2S2
velveth /scratch/cputonti/v2S1Xv2S2 29 -short -fasta /data/cputonti/v2_S1/contigs.fa /data/cputonti/v2_S2/contigs.fa

velvetg /scratch/cputonti/v2S1Xv2S2 -exp_cov auto

#v2S1Xv2S3
velveth /scratch/cputonti/v2S1Xv2S3 29 -short -fasta /data/cputonti/v2_S1/contigs.fa /data/cputonti/v2_S3/contigs.fa

velvetg /scratch/cputonti/v2S1Xv2S3 -exp_cov auto

#v2S1Xv2S4
velveth /scratch/cputonti/v2S1Xv2S4 29 -short -fasta /data/cputonti/v2_S1/contigs.fa /data/cputonti/v2_S4/contigs.fa

velvetg /scratch/cputonti/v2S1Xv2S4 -exp_cov auto

#v2S1Xv2S5
velveth /scratch/cputonti/v2S1Xv2S5 29 -short -fasta /data/cputonti/v2_S1/contigs.fa /data/cputonti/v2_S5/contigs.fa

velvetg /scratch/cputonti/v2S1Xv2S5 -exp_cov auto

#v2S1Xv2S6
velveth /scratch/cputonti/v2S1Xv2S6 29 -short -fasta /data/cputonti/v2_S1/contigs.fa /data/cputonti/v2_S6/contigs.fa

velvetg /scratch/cputonti/v2S1Xv2S6 -exp_cov auto

#v2S1Xv2S7
velveth /scratch/cputonti/v2S1Xv2S7 29 -short -fasta /data/cputonti/v2_S1/contigs.fa /data/cputonti/v2_S7/contigs.fa

velvetg /scratch/cputonti/v2S1Xv2S7 -exp_cov auto

#v2S1Xv2S8
velveth /scratch/cputonti/v2S1Xv2S8 29 -short -fasta /data/cputonti/v2_S1/contigs.fa /data/cputonti/v2_S8/contigs.fa

velvetg /scratch/cputonti/v2S1Xv2S8 -exp_cov auto

#v2S1Xv2S9
velveth /scratch/cputonti/v2S1Xv2S9 29 -short -fasta /data/cputonti/v2_S1/contigs.fa /data/cputonti/v2_S9/contigs.fa

velvetg /scratch/cputonti/v2S1Xv2S9 -exp_cov auto

#v2S1Xv2S10
velveth /scratch/cputonti/v2S1Xv2S10 29 -short -fasta /data/cputonti/v2_S1/contigs.fa /data/cputonti/v2_S10/contigs.fa

velvetg /scratch/cputonti/v2S1Xv2S10 -exp_cov auto

#v2S1Xv2S11
velveth /scratch/cputonti/v2S1Xv2S11 29 -short -fasta /data/cputonti/v2_S1/contigs.fa /data/cputonti/v2_S11/contigs.fa

velvetg /scratch/cputonti/v2S1Xv2S11 -exp_cov auto

#v2S2Xv2S3
velveth /scratch/cputonti/v2S2Xv2S3 29 -short -fasta /data/cputonti/v2_S2/contigs.fa /data/cputonti/v2_S3/contigs.fa

velvetg /scratch/cputonti/v2S2Xv2S3 -exp_cov auto

#v2S2Xv2S4
velveth /scratch/cputonti/v2S2Xv2S4 29 -short -fasta /data/cputonti/v2_S2/contigs.fa /data/cputonti/v2_S4/contigs.fa

velvetg /scratch/cputonti/v2S2Xv2S4 -exp_cov auto

#v2S2Xv2S5
velveth /scratch/cputonti/v2S2Xv2S5 29 -short -fasta /data/cputonti/v2_S2/contigs.fa /data/cputonti/v2_S5/contigs.fa

velvetg /scratch/cputonti/v2S2Xv2S5 -exp_cov auto

#v2S2Xv2S6
velveth /scratch/cputonti/v2S2Xv2S6 29 -short -fasta /data/cputonti/v2_S2/contigs.fa /data/cputonti/v2_S6/contigs.fa

velvetg /scratch/cputonti/v2S2Xv2S6 -exp_cov auto

#v2S2Xv2S7
velveth /scratch/cputonti/v2S2Xv2S7 29 -short -fasta /data/cputonti/v2_S2/contigs.fa /data/cputonti/v2_S7/contigs.fa

velvetg /scratch/cputonti/v2S2Xv2S7 -exp_cov auto

#v2S2Xv2S8
velveth /scratch/cputonti/v2S2Xv2S8 29 -short -fasta /data/cputonti/v2_S2/contigs.fa /data/cputonti/v2_S8/contigs.fa

velvetg /scratch/cputonti/v2S2Xv2S8 -exp_cov auto

#v2S2Xv2S9
velveth /scratch/cputonti/v2S2Xv2S9 29 -short -fasta /data/cputonti/v2_S2/contigs.fa /data/cputonti/v2_S9/contigs.fa

velvetg /scratch/cputonti/v2S2Xv2S9 -exp_cov auto

#v2S2Xv2S10
velveth /scratch/cputonti/v2S2Xv2S10 29 -short -fasta /data/cputonti/v2_S2/contigs.fa /data/cputonti/v2_S10/contigs.fa

velvetg /scratch/cputonti/v2S2Xv2S10 -exp_cov auto

#v2S2Xv2S11
velveth /scratch/cputonti/v2S2Xv2S11 29 -short -fasta /data/cputonti/v2_S2/contigs.fa /data/cputonti/v2_S11/contigs.fa

velvetg /scratch/cputonti/v2S2Xv2S11 -exp_cov auto

#v2S3Xv2S4
velveth /scratch/cputonti/v2S3Xv2S4 29 -short -fasta /data/cputonti/v2_S3/contigs.fa /data/cputonti/v2_S4/contigs.fa

velvetg /scratch/cputonti/v2S3Xv2S4 -exp_cov auto

#v2S3Xv2S5
velveth /scratch/cputonti/v2S3Xv2S5 29 -short -fasta /data/cputonti/v2_S3/contigs.fa /data/cputonti/v2_S5/contigs.fa

velvetg /scratch/cputonti/v2S3Xv2S5 -exp_cov auto

#v2S3Xv2S6
velveth /scratch/cputonti/v2S3Xv2S6 29 -short -fasta /data/cputonti/v2_S3/contigs.fa /data/cputonti/v2_S6/contigs.fa

velvetg /scratch/cputonti/v2S3Xv2S6 -exp_cov auto

#v2S3Xv2S7
velveth /scratch/cputonti/v2S3Xv2S7 29 -short -fasta /data/cputonti/v2_S3/contigs.fa /data/cputonti/v2_S7/contigs.fa

velvetg /scratch/cputonti/v2S3Xv2S7 -exp_cov auto

#v2S3Xv2S8
velveth /scratch/cputonti/v2S3Xv2S8 29 -short -fasta /data/cputonti/v2_S3/contigs.fa /data/cputonti/v2_S8/contigs.fa

velvetg /scratch/cputonti/v2S3Xv2S8 -exp_cov auto

#v2S3Xv2S9
velveth /scratch/cputonti/v2S3Xv2S9 29 -short -fasta /data/cputonti/v2_S3/contigs.fa /data/cputonti/v2_S9/contigs.fa

velvetg /scratch/cputonti/v2S3Xv2S9 -exp_cov auto

#v2S3Xv2S10
velveth /scratch/cputonti/v2S3Xv2S10 29 -short -fasta /data/cputonti/v2_S3/contigs.fa /data/cputonti/v2_S10/contigs.fa

velvetg /scratch/cputonti/v2S3Xv2S10 -exp_cov auto

#v2S3Xv2S11
velveth /scratch/cputonti/v2S3Xv2S11 29 -short -fasta /data/cputonti/v2_S3/contigs.fa /data/cputonti/v2_S11/contigs.fa

velvetg /scratch/cputonti/v2S3Xv2S11 -exp_cov auto

#v2S4Xv2S5
velveth /scratch/cputonti/v2S4Xv2S5 29 -short -fasta /data/cputonti/v2_S4/contigs.fa /data/cputonti/v2_S5/contigs.fa

velvetg /scratch/cputonti/v2S4Xv2S5 -exp_cov auto

#v2S4Xv2S6
velveth /scratch/cputonti/v2S4Xv2S6 29 -short -fasta /data/cputonti/v2_S4/contigs.fa /data/cputonti/v2_S6/contigs.fa

velvetg /scratch/cputonti/v2S4Xv2S6 -exp_cov auto

#v2S4Xv2S7
velveth /scratch/cputonti/v2S4Xv2S7 29 -short -fasta /data/cputonti/v2_S4/contigs.fa /data/cputonti/v2_S7/contigs.fa

velvetg /scratch/cputonti/v2S4Xv2S7 -exp_cov auto

#v2S4Xv2S8
velveth /scratch/cputonti/v2S4Xv2S8 29 -short -fasta /data/cputonti/v2_S4/contigs.fa /data/cputonti/v2_S8/contigs.fa

velvetg /scratch/cputonti/v2S4Xv2S8 -exp_cov auto

#v2S4Xv2S9
velveth /scratch/cputonti/v2S4Xv2S9 29 -short -fasta /data/cputonti/v2_S4/contigs.fa /data/cputonti/v2_S9/contigs.fa

velvetg /scratch/cputonti/v2S4Xv2S9 -exp_cov auto

#v2S4Xv2S10
velveth /scratch/cputonti/v2S4Xv2S10 29 -short -fasta /data/cputonti/v2_S4/contigs.fa /data/cputonti/v2_S10/contigs.fa

velvetg /scratch/cputonti/v2S4Xv2S10 -exp_cov auto

#v2S4Xv2S11
velveth /scratch/cputonti/v2S4Xv2S11 29 -short -fasta /data/cputonti/v2_S4/contigs.fa /data/cputonti/v2_S11/contigs.fa

velvetg /scratch/cputonti/v2S4Xv2S11 -exp_cov auto

#v2S5Xv2S6
velveth /scratch/cputonti/v2S5Xv2S6 29 -short -fasta /data/cputonti/v2_S5/contigs.fa /data/cputonti/v2_S6/contigs.fa

velvetg /scratch/cputonti/v2S5Xv2S6 -exp_cov auto

#v2S5Xv2S7
velveth /scratch/cputonti/v2S5Xv2S7 29 -short -fasta /data/cputonti/v2_S5/contigs.fa /data/cputonti/v2_S7/contigs.fa

velvetg /scratch/cputonti/v2S5Xv2S7 -exp_cov auto

#v2S5Xv2S8
velveth /scratch/cputonti/v2S5Xv2S8 29 -short -fasta /data/cputonti/v2_S5/contigs.fa /data/cputonti/v2_S8/contigs.fa

velvetg /scratch/cputonti/v2S5Xv2S8 -exp_cov auto

#v2S5Xv2S9
velveth /scratch/cputonti/v2S5Xv2S9 29 -short -fasta /data/cputonti/v2_S5/contigs.fa /data/cputonti/v2_S9/contigs.fa

velvetg /scratch/cputonti/v2S5Xv2S9 -exp_cov auto

#v2S5Xv2S10
velveth /scratch/cputonti/v2S5Xv2S10 29 -short -fasta /data/cputonti/v2_S5/contigs.fa /data/cputonti/v2_S10/contigs.fa

velvetg /scratch/cputonti/v2S5Xv2S10 -exp_cov auto

#v2S5Xv2S11
velveth /scratch/cputonti/v2S5Xv2S11 29 -short -fasta /data/cputonti/v2_S5/contigs.fa /data/cputonti/v2_S11/contigs.fa

velvetg /scratch/cputonti/v2S5Xv2S11 -exp_cov auto

#v2S6Xv2S7
velveth /scratch/cputonti/v2S6Xv2S7 29 -short -fasta /data/cputonti/v2_S6/contigs.fa /data/cputonti/v2_S7/contigs.fa

velvetg /scratch/cputonti/v2S6Xv2S7 -exp_cov auto

#v2S6Xv2S8
velveth /scratch/cputonti/v2S6Xv2S8 29 -short -fasta /data/cputonti/v2_S6/contigs.fa /data/cputonti/v2_S8/contigs.fa

velvetg /scratch/cputonti/v2S6Xv2S8 -exp_cov auto

#v2S6Xv2S9
velveth /scratch/cputonti/v2S6Xv2S9 29 -short -fasta /data/cputonti/v2_S6/contigs.fa /data/cputonti/v2_S9/contigs.fa

velvetg /scratch/cputonti/v2S6Xv2S9 -exp_cov auto

#v2S6Xv2S10
velveth /scratch/cputonti/v2S6Xv2S10 29 -short -fasta /data/cputonti/v2_S6/contigs.fa /data/cputonti/v2_S10/contigs.fa

velvetg /scratch/cputonti/v2S6Xv2S10 -exp_cov auto

#v2S6Xv2S11
velveth /scratch/cputonti/v2S6Xv2S11 29 -short -fasta /data/cputonti/v2_S6/contigs.fa /data/cputonti/v2_S11/contigs.fa

velvetg /scratch/cputonti/v2S6Xv2S11 -exp_cov auto

#v2S7Xv2S8
velveth /scratch/cputonti/v2S7Xv2S8 29 -short -fasta /data/cputonti/v2_S7/contigs.fa /data/cputonti/v2_S8/contigs.fa

velvetg /scratch/cputonti/v2S7Xv2S8 -exp_cov auto

#v2S7Xv2S9
velveth /scratch/cputonti/v2S7Xv2S9 29 -short -fasta /data/cputonti/v2_S7/contigs.fa /data/cputonti/v2_S9/contigs.fa

velvetg /scratch/cputonti/v2S7Xv2S9 -exp_cov auto

#v2S7Xv2S10
velveth /scratch/cputonti/v2S7Xv2S10 29 -short -fasta /data/cputonti/v2_S7/contigs.fa /data/cputonti/v2_S10/contigs.fa

velvetg /scratch/cputonti/v2S7Xv2S10 -exp_cov auto

#v2S7Xv2S11
velveth /scratch/cputonti/v2S7Xv2S11 29 -short -fasta /data/cputonti/v2_S7/contigs.fa /data/cputonti/v2_S11/contigs.fa

velvetg /scratch/cputonti/v2S7Xv2S11 -exp_cov auto

#v2S8Xv2S9
velveth /scratch/cputonti/v2S8Xv2S9 29 -short -fasta /data/cputonti/v2_S8/contigs.fa /data/cputonti/v2_S9/contigs.fa

velvetg /scratch/cputonti/v2S8Xv2S9 -exp_cov auto

#v2S8Xv2S10
velveth /scratch/cputonti/v2S8Xv2S10 29 -short -fasta /data/cputonti/v2_S8/contigs.fa /data/cputonti/v2_S10/contigs.fa

velvetg /scratch/cputonti/v2S8Xv2S10 -exp_cov auto

#v2S8Xv2S11
velveth /scratch/cputonti/v2S8Xv2S11 29 -short -fasta /data/cputonti/v2_S8/contigs.fa /data/cputonti/v2_S11/contigs.fa

velvetg /scratch/cputonti/v2S8Xv2S11 -exp_cov auto

#v2S9Xv2S10
velveth /scratch/cputonti/v2S9Xv2S10 29 -short -fasta /data/cputonti/v2_S9/contigs.fa /data/cputonti/v2_S10/contigs.fa

velvetg /scratch/cputonti/v2S9Xv2S10 -exp_cov auto

#v2S9Xv2S11
velveth /scratch/cputonti/v2S9Xv2S11 29 -short -fasta /data/cputonti/v2_S9/contigs.fa /data/cputonti/v2_S11/contigs.fa

velvetg /scratch/cputonti/v2S9Xv2S11 -exp_cov auto

#v2S10Xv2S11
velveth /scratch/cputonti/v2S10Xv2S11 29 -short -fasta /data/cputonti/v2_S10/contigs.fa /data/cputonti/v2_S11/contigs.fa

velvetg /scratch/cputonti/v2S10Xv2S11 -exp_cov auto